---
- name: Schedule at task
  #After waiting one minute for the at command to complete, run ad hoc commands to
  #verify that the /home/devops/my_at_date_time file exists and has the correct
  #contents.
  hosts: webservers
  become: true
  become_user: devops
  tasks:
    - name: Create date and time file
      at:
        command: "date > ~/my_at_date_time\n"
        count: 1
        units: minutes
        unique: yes
        state: present
