---
- name: Install Apache web server
  hosts: prod_servers
  become: yes

  tasks:
  - name: Install Apache web Server
    yum: name=apache2 state=latest

  - name: Start Apache and enable it
    service: name=apache2 state=started enabled=yes  
