---
- name  : Install Apache server and upload my Web Page
  hosts: prod_servers
  become: yes
  

  vars:
    source_files: ./mywebsite/index.html
    destin_file : /var/www/html
  

  tasks:
  - name: Install Web Apache Server
    yum : name=apache2 state=latest

  - name: Copy My Home Page
    copy: src= {{ source_files }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start Web Server and make it enable on boot
    service: name=apache2 state=started enabled=yes



  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted  
